name: Self hoster
on: [push, workflow_dispatch]
jobs:
  go-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        run: DD_ENV=ci-java-carlos ./gradlew clean -Pdd-civisibility -x test --rerun-tasks
